// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mc/jabber/proto/protos/circuitBoardBuffer.proto

package mc.jabber.proto;

public final class CircuitBoardBuffer {
  private CircuitBoardBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CircuitBoardProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mc.jabber.proto.CircuitBoardProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sizeX = 1;</code>
     * @return The sizeX.
     */
    int getSizeX();

    /**
     * <code>int32 sizeY = 2;</code>
     * @return The sizeY.
     */
    int getSizeY();

    /**
     * <code>map&lt;int32, string&gt; entries = 3;</code>
     */
    int getEntriesCount();
    /**
     * <code>map&lt;int32, string&gt; entries = 3;</code>
     */
    boolean containsEntries(
        int key);
    /**
     * Use {@link #getEntriesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.String>
    getEntries();
    /**
     * <code>map&lt;int32, string&gt; entries = 3;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.String>
    getEntriesMap();
    /**
     * <code>map&lt;int32, string&gt; entries = 3;</code>
     */

    java.lang.String getEntriesOrDefault(
        int key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;int32, string&gt; entries = 3;</code>
     */

    java.lang.String getEntriesOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code mc.jabber.proto.CircuitBoardProto}
   */
  public static final class CircuitBoardProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mc.jabber.proto.CircuitBoardProto)
      CircuitBoardProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CircuitBoardProto.newBuilder() to construct.
    private CircuitBoardProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CircuitBoardProto() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CircuitBoardProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CircuitBoardProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sizeX_ = input.readInt32();
              break;
            }
            case 16: {

              sizeY_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                entries_ = com.google.protobuf.MapField.newMapField(
                    EntriesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
              entries__ = input.readMessage(
                  EntriesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              entries_.getMutableMap().put(
                  entries__.getKey(), entries__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mc.jabber.proto.CircuitBoardBuffer.internal_static_mc_jabber_proto_CircuitBoardProto_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetEntries();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mc.jabber.proto.CircuitBoardBuffer.internal_static_mc_jabber_proto_CircuitBoardProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto.class, mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto.Builder.class);
    }

    public static final int SIZEX_FIELD_NUMBER = 1;
    private int sizeX_;
    /**
     * <code>int32 sizeX = 1;</code>
     * @return The sizeX.
     */
    @java.lang.Override
    public int getSizeX() {
      return sizeX_;
    }

    public static final int SIZEY_FIELD_NUMBER = 2;
    private int sizeY_;
    /**
     * <code>int32 sizeY = 2;</code>
     * @return The sizeY.
     */
    @java.lang.Override
    public int getSizeY() {
      return sizeY_;
    }

    public static final int ENTRIES_FIELD_NUMBER = 3;
    private static final class EntriesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.String>newDefaultInstance(
                  mc.jabber.proto.CircuitBoardBuffer.internal_static_mc_jabber_proto_CircuitBoardProto_EntriesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.String> entries_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
    internalGetEntries() {
      if (entries_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EntriesDefaultEntryHolder.defaultEntry);
      }
      return entries_;
    }

    public int getEntriesCount() {
      return internalGetEntries().getMap().size();
    }
    /**
     * <code>map&lt;int32, string&gt; entries = 3;</code>
     */

    @java.lang.Override
    public boolean containsEntries(
        int key) {
      
      return internalGetEntries().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEntriesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String> getEntries() {
      return getEntriesMap();
    }
    /**
     * <code>map&lt;int32, string&gt; entries = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, java.lang.String> getEntriesMap() {
      return internalGetEntries().getMap();
    }
    /**
     * <code>map&lt;int32, string&gt; entries = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getEntriesOrDefault(
        int key,
        java.lang.String defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetEntries().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, string&gt; entries = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getEntriesOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetEntries().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sizeX_ != 0) {
        output.writeInt32(1, sizeX_);
      }
      if (sizeY_ != 0) {
        output.writeInt32(2, sizeY_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetEntries(),
          EntriesDefaultEntryHolder.defaultEntry,
          3);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sizeX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sizeX_);
      }
      if (sizeY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sizeY_);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
           : internalGetEntries().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
        entries__ = EntriesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, entries__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto)) {
        return super.equals(obj);
      }
      mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto other = (mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto) obj;

      if (getSizeX()
          != other.getSizeX()) return false;
      if (getSizeY()
          != other.getSizeY()) return false;
      if (!internalGetEntries().equals(
          other.internalGetEntries())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIZEX_FIELD_NUMBER;
      hash = (53 * hash) + getSizeX();
      hash = (37 * hash) + SIZEY_FIELD_NUMBER;
      hash = (53 * hash) + getSizeY();
      if (!internalGetEntries().getMap().isEmpty()) {
        hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetEntries().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mc.jabber.proto.CircuitBoardProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mc.jabber.proto.CircuitBoardProto)
        mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mc.jabber.proto.CircuitBoardBuffer.internal_static_mc_jabber_proto_CircuitBoardProto_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetEntries();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableEntries();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mc.jabber.proto.CircuitBoardBuffer.internal_static_mc_jabber_proto_CircuitBoardProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto.class, mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto.Builder.class);
      }

      // Construct using mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sizeX_ = 0;

        sizeY_ = 0;

        internalGetMutableEntries().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mc.jabber.proto.CircuitBoardBuffer.internal_static_mc_jabber_proto_CircuitBoardProto_descriptor;
      }

      @java.lang.Override
      public mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto getDefaultInstanceForType() {
        return mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto.getDefaultInstance();
      }

      @java.lang.Override
      public mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto build() {
        mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto buildPartial() {
        mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto result = new mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto(this);
        int from_bitField0_ = bitField0_;
        result.sizeX_ = sizeX_;
        result.sizeY_ = sizeY_;
        result.entries_ = internalGetEntries();
        result.entries_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto) {
          return mergeFrom((mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto other) {
        if (other == mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto.getDefaultInstance()) return this;
        if (other.getSizeX() != 0) {
          setSizeX(other.getSizeX());
        }
        if (other.getSizeY() != 0) {
          setSizeY(other.getSizeY());
        }
        internalGetMutableEntries().mergeFrom(
            other.internalGetEntries());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sizeX_ ;
      /**
       * <code>int32 sizeX = 1;</code>
       * @return The sizeX.
       */
      @java.lang.Override
      public int getSizeX() {
        return sizeX_;
      }
      /**
       * <code>int32 sizeX = 1;</code>
       * @param value The sizeX to set.
       * @return This builder for chaining.
       */
      public Builder setSizeX(int value) {
        
        sizeX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sizeX = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSizeX() {
        
        sizeX_ = 0;
        onChanged();
        return this;
      }

      private int sizeY_ ;
      /**
       * <code>int32 sizeY = 2;</code>
       * @return The sizeY.
       */
      @java.lang.Override
      public int getSizeY() {
        return sizeY_;
      }
      /**
       * <code>int32 sizeY = 2;</code>
       * @param value The sizeY to set.
       * @return This builder for chaining.
       */
      public Builder setSizeY(int value) {
        
        sizeY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sizeY = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSizeY() {
        
        sizeY_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.String> entries_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetEntries() {
        if (entries_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              EntriesDefaultEntryHolder.defaultEntry);
        }
        return entries_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetMutableEntries() {
        onChanged();;
        if (entries_ == null) {
          entries_ = com.google.protobuf.MapField.newMapField(
              EntriesDefaultEntryHolder.defaultEntry);
        }
        if (!entries_.isMutable()) {
          entries_ = entries_.copy();
        }
        return entries_;
      }

      public int getEntriesCount() {
        return internalGetEntries().getMap().size();
      }
      /**
       * <code>map&lt;int32, string&gt; entries = 3;</code>
       */

      @java.lang.Override
      public boolean containsEntries(
          int key) {
        
        return internalGetEntries().getMap().containsKey(key);
      }
      /**
       * Use {@link #getEntriesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String> getEntries() {
        return getEntriesMap();
      }
      /**
       * <code>map&lt;int32, string&gt; entries = 3;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Integer, java.lang.String> getEntriesMap() {
        return internalGetEntries().getMap();
      }
      /**
       * <code>map&lt;int32, string&gt; entries = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getEntriesOrDefault(
          int key,
          java.lang.String defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetEntries().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, string&gt; entries = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getEntriesOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetEntries().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearEntries() {
        internalGetMutableEntries().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, string&gt; entries = 3;</code>
       */

      public Builder removeEntries(
          int key) {
        
        internalGetMutableEntries().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String>
      getMutableEntries() {
        return internalGetMutableEntries().getMutableMap();
      }
      /**
       * <code>map&lt;int32, string&gt; entries = 3;</code>
       */
      public Builder putEntries(
          int key,
          java.lang.String value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableEntries().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, string&gt; entries = 3;</code>
       */

      public Builder putAllEntries(
          java.util.Map<java.lang.Integer, java.lang.String> values) {
        internalGetMutableEntries().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mc.jabber.proto.CircuitBoardProto)
    }

    // @@protoc_insertion_point(class_scope:mc.jabber.proto.CircuitBoardProto)
    private static final mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto();
    }

    public static mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CircuitBoardProto>
        PARSER = new com.google.protobuf.AbstractParser<CircuitBoardProto>() {
      @java.lang.Override
      public CircuitBoardProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CircuitBoardProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CircuitBoardProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CircuitBoardProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mc.jabber.proto.CircuitBoardBuffer.CircuitBoardProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_jabber_proto_CircuitBoardProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mc_jabber_proto_CircuitBoardProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_jabber_proto_CircuitBoardProto_EntriesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mc_jabber_proto_CircuitBoardProto_EntriesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/mc/jabber/proto/protos/circuitBoardBuf" +
      "fer.proto\022\017mc.jabber.proto\"\243\001\n\021CircuitBo" +
      "ardProto\022\r\n\005sizeX\030\001 \001(\005\022\r\n\005sizeY\030\002 \001(\005\022@" +
      "\n\007entries\030\003 \003(\0132/.mc.jabber.proto.Circui" +
      "tBoardProto.EntriesEntry\032.\n\014EntriesEntry" +
      "\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\t:\0028\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mc_jabber_proto_CircuitBoardProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mc_jabber_proto_CircuitBoardProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mc_jabber_proto_CircuitBoardProto_descriptor,
        new java.lang.String[] { "SizeX", "SizeY", "Entries", });
    internal_static_mc_jabber_proto_CircuitBoardProto_EntriesEntry_descriptor =
      internal_static_mc_jabber_proto_CircuitBoardProto_descriptor.getNestedTypes().get(0);
    internal_static_mc_jabber_proto_CircuitBoardProto_EntriesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mc_jabber_proto_CircuitBoardProto_EntriesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
