// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mc/jabber/proto/protos/delayChipStateBuffer.proto

package mc.jabber.proto;

public final class DelayChipStateBuffer {
  private DelayChipStateBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DelayChipStateProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mc.jabber.proto.DelayChipStateProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
     */
    java.util.List<mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry> 
        getEntriesList();
    /**
     * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
     */
    mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry getEntries(int index);
    /**
     * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
     */
    int getEntriesCount();
    /**
     * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
     */
    java.util.List<? extends mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entryOrBuilder> 
        getEntriesOrBuilderList();
    /**
     * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
     */
    mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entryOrBuilder getEntriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code mc.jabber.proto.DelayChipStateProto}
   */
  public static final class DelayChipStateProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mc.jabber.proto.DelayChipStateProto)
      DelayChipStateProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DelayChipStateProto.newBuilder() to construct.
    private DelayChipStateProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DelayChipStateProto() {
      entries_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DelayChipStateProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DelayChipStateProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                entries_ = new java.util.ArrayList<mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry>();
                mutable_bitField0_ |= 0x00000001;
              }
              entries_.add(
                  input.readMessage(mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mc.jabber.proto.DelayChipStateBuffer.internal_static_mc_jabber_proto_DelayChipStateProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mc.jabber.proto.DelayChipStateBuffer.internal_static_mc_jabber_proto_DelayChipStateProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.class, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.Builder.class);
    }

    public interface entryOrBuilder extends
        // @@protoc_insertion_point(interface_extends:mc.jabber.proto.DelayChipStateProto.entry)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>uint32 remainingDelay = 1;</code>
       * @return The remainingDelay.
       */
      int getRemainingDelay();

      /**
       * <code>uint32 direction = 2;</code>
       * @return The direction.
       */
      int getDirection();

      /**
       * <code>int64 data = 3;</code>
       * @return The data.
       */
      long getData();
    }
    /**
     * Protobuf type {@code mc.jabber.proto.DelayChipStateProto.entry}
     */
    public static final class entry extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:mc.jabber.proto.DelayChipStateProto.entry)
        entryOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use entry.newBuilder() to construct.
      private entry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private entry() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new entry();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private entry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                remainingDelay_ = input.readUInt32();
                break;
              }
              case 16: {

                direction_ = input.readUInt32();
                break;
              }
              case 24: {

                data_ = input.readInt64();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mc.jabber.proto.DelayChipStateBuffer.internal_static_mc_jabber_proto_DelayChipStateProto_entry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mc.jabber.proto.DelayChipStateBuffer.internal_static_mc_jabber_proto_DelayChipStateProto_entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.class, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.Builder.class);
      }

      public static final int REMAININGDELAY_FIELD_NUMBER = 1;
      private int remainingDelay_;
      /**
       * <code>uint32 remainingDelay = 1;</code>
       * @return The remainingDelay.
       */
      @java.lang.Override
      public int getRemainingDelay() {
        return remainingDelay_;
      }

      public static final int DIRECTION_FIELD_NUMBER = 2;
      private int direction_;
      /**
       * <code>uint32 direction = 2;</code>
       * @return The direction.
       */
      @java.lang.Override
      public int getDirection() {
        return direction_;
      }

      public static final int DATA_FIELD_NUMBER = 3;
      private long data_;
      /**
       * <code>int64 data = 3;</code>
       * @return The data.
       */
      @java.lang.Override
      public long getData() {
        return data_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (remainingDelay_ != 0) {
          output.writeUInt32(1, remainingDelay_);
        }
        if (direction_ != 0) {
          output.writeUInt32(2, direction_);
        }
        if (data_ != 0L) {
          output.writeInt64(3, data_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (remainingDelay_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, remainingDelay_);
        }
        if (direction_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, direction_);
        }
        if (data_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, data_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry)) {
          return super.equals(obj);
        }
        mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry other = (mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry) obj;

        if (getRemainingDelay()
            != other.getRemainingDelay()) return false;
        if (getDirection()
            != other.getDirection()) return false;
        if (getData()
            != other.getData()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + REMAININGDELAY_FIELD_NUMBER;
        hash = (53 * hash) + getRemainingDelay();
        hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
        hash = (53 * hash) + getDirection();
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getData());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code mc.jabber.proto.DelayChipStateProto.entry}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:mc.jabber.proto.DelayChipStateProto.entry)
          mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return mc.jabber.proto.DelayChipStateBuffer.internal_static_mc_jabber_proto_DelayChipStateProto_entry_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return mc.jabber.proto.DelayChipStateBuffer.internal_static_mc_jabber_proto_DelayChipStateProto_entry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.class, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.Builder.class);
        }

        // Construct using mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          remainingDelay_ = 0;

          direction_ = 0;

          data_ = 0L;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return mc.jabber.proto.DelayChipStateBuffer.internal_static_mc_jabber_proto_DelayChipStateProto_entry_descriptor;
        }

        @java.lang.Override
        public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry getDefaultInstanceForType() {
          return mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.getDefaultInstance();
        }

        @java.lang.Override
        public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry build() {
          mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry buildPartial() {
          mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry result = new mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry(this);
          result.remainingDelay_ = remainingDelay_;
          result.direction_ = direction_;
          result.data_ = data_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry) {
            return mergeFrom((mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry other) {
          if (other == mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.getDefaultInstance()) return this;
          if (other.getRemainingDelay() != 0) {
            setRemainingDelay(other.getRemainingDelay());
          }
          if (other.getDirection() != 0) {
            setDirection(other.getDirection());
          }
          if (other.getData() != 0L) {
            setData(other.getData());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int remainingDelay_ ;
        /**
         * <code>uint32 remainingDelay = 1;</code>
         * @return The remainingDelay.
         */
        @java.lang.Override
        public int getRemainingDelay() {
          return remainingDelay_;
        }
        /**
         * <code>uint32 remainingDelay = 1;</code>
         * @param value The remainingDelay to set.
         * @return This builder for chaining.
         */
        public Builder setRemainingDelay(int value) {
          
          remainingDelay_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 remainingDelay = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearRemainingDelay() {
          
          remainingDelay_ = 0;
          onChanged();
          return this;
        }

        private int direction_ ;
        /**
         * <code>uint32 direction = 2;</code>
         * @return The direction.
         */
        @java.lang.Override
        public int getDirection() {
          return direction_;
        }
        /**
         * <code>uint32 direction = 2;</code>
         * @param value The direction to set.
         * @return This builder for chaining.
         */
        public Builder setDirection(int value) {
          
          direction_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 direction = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearDirection() {
          
          direction_ = 0;
          onChanged();
          return this;
        }

        private long data_ ;
        /**
         * <code>int64 data = 3;</code>
         * @return The data.
         */
        @java.lang.Override
        public long getData() {
          return data_;
        }
        /**
         * <code>int64 data = 3;</code>
         * @param value The data to set.
         * @return This builder for chaining.
         */
        public Builder setData(long value) {
          
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 data = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearData() {
          
          data_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:mc.jabber.proto.DelayChipStateProto.entry)
      }

      // @@protoc_insertion_point(class_scope:mc.jabber.proto.DelayChipStateProto.entry)
      private static final mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry();
      }

      public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<entry>
          PARSER = new com.google.protobuf.AbstractParser<entry>() {
        @java.lang.Override
        public entry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new entry(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<entry> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<entry> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ENTRIES_FIELD_NUMBER = 1;
    private java.util.List<mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry> entries_;
    /**
     * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
     */
    @java.lang.Override
    public java.util.List<mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry> getEntriesList() {
      return entries_;
    }
    /**
     * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entryOrBuilder> 
        getEntriesOrBuilderList() {
      return entries_;
    }
    /**
     * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
     */
    @java.lang.Override
    public int getEntriesCount() {
      return entries_.size();
    }
    /**
     * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
     */
    @java.lang.Override
    public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry getEntries(int index) {
      return entries_.get(index);
    }
    /**
     * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
     */
    @java.lang.Override
    public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entryOrBuilder getEntriesOrBuilder(
        int index) {
      return entries_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < entries_.size(); i++) {
        output.writeMessage(1, entries_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < entries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entries_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto)) {
        return super.equals(obj);
      }
      mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto other = (mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto) obj;

      if (!getEntriesList()
          .equals(other.getEntriesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEntriesCount() > 0) {
        hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
        hash = (53 * hash) + getEntriesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mc.jabber.proto.DelayChipStateProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mc.jabber.proto.DelayChipStateProto)
        mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mc.jabber.proto.DelayChipStateBuffer.internal_static_mc_jabber_proto_DelayChipStateProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mc.jabber.proto.DelayChipStateBuffer.internal_static_mc_jabber_proto_DelayChipStateProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.class, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.Builder.class);
      }

      // Construct using mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEntriesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mc.jabber.proto.DelayChipStateBuffer.internal_static_mc_jabber_proto_DelayChipStateProto_descriptor;
      }

      @java.lang.Override
      public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto getDefaultInstanceForType() {
        return mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.getDefaultInstance();
      }

      @java.lang.Override
      public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto build() {
        mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto buildPartial() {
        mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto result = new mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto(this);
        int from_bitField0_ = bitField0_;
        if (entriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            entries_ = java.util.Collections.unmodifiableList(entries_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entries_ = entries_;
        } else {
          result.entries_ = entriesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto) {
          return mergeFrom((mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto other) {
        if (other == mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.getDefaultInstance()) return this;
        if (entriesBuilder_ == null) {
          if (!other.entries_.isEmpty()) {
            if (entries_.isEmpty()) {
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntriesIsMutable();
              entries_.addAll(other.entries_);
            }
            onChanged();
          }
        } else {
          if (!other.entries_.isEmpty()) {
            if (entriesBuilder_.isEmpty()) {
              entriesBuilder_.dispose();
              entriesBuilder_ = null;
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000001);
              entriesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEntriesFieldBuilder() : null;
            } else {
              entriesBuilder_.addAllMessages(other.entries_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry> entries_ =
        java.util.Collections.emptyList();
      private void ensureEntriesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          entries_ = new java.util.ArrayList<mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry>(entries_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.Builder, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entryOrBuilder> entriesBuilder_;

      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public java.util.List<mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry> getEntriesList() {
        if (entriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entries_);
        } else {
          return entriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public int getEntriesCount() {
        if (entriesBuilder_ == null) {
          return entries_.size();
        } else {
          return entriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry getEntries(int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);
        } else {
          return entriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public Builder setEntries(
          int index, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.set(index, value);
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public Builder setEntries(
          int index, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.set(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public Builder addEntries(mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public Builder addEntries(
          int index, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(index, value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public Builder addEntries(
          mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public Builder addEntries(
          int index, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public Builder addAllEntries(
          java.lang.Iterable<? extends mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry> values) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, entries_);
          onChanged();
        } else {
          entriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public Builder clearEntries() {
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public Builder removeEntries(int index) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.remove(index);
          onChanged();
        } else {
          entriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.Builder getEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entryOrBuilder getEntriesOrBuilder(
          int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);  } else {
          return entriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public java.util.List<? extends mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entryOrBuilder> 
           getEntriesOrBuilderList() {
        if (entriesBuilder_ != null) {
          return entriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entries_);
        }
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.Builder addEntriesBuilder() {
        return getEntriesFieldBuilder().addBuilder(
            mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.getDefaultInstance());
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.Builder addEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().addBuilder(
            index, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.getDefaultInstance());
      }
      /**
       * <code>repeated .mc.jabber.proto.DelayChipStateProto.entry entries = 1;</code>
       */
      public java.util.List<mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.Builder> 
           getEntriesBuilderList() {
        return getEntriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.Builder, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entryOrBuilder> 
          getEntriesFieldBuilder() {
        if (entriesBuilder_ == null) {
          entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entry.Builder, mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto.entryOrBuilder>(
                  entries_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          entries_ = null;
        }
        return entriesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mc.jabber.proto.DelayChipStateProto)
    }

    // @@protoc_insertion_point(class_scope:mc.jabber.proto.DelayChipStateProto)
    private static final mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto();
    }

    public static mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DelayChipStateProto>
        PARSER = new com.google.protobuf.AbstractParser<DelayChipStateProto>() {
      @java.lang.Override
      public DelayChipStateProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DelayChipStateProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DelayChipStateProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DelayChipStateProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mc.jabber.proto.DelayChipStateBuffer.DelayChipStateProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_jabber_proto_DelayChipStateProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mc_jabber_proto_DelayChipStateProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_jabber_proto_DelayChipStateProto_entry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mc_jabber_proto_DelayChipStateProto_entry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1mc/jabber/proto/protos/delayChipStateB" +
      "uffer.proto\022\017mc.jabber.proto\"\224\001\n\023DelayCh" +
      "ipStateProto\022;\n\007entries\030\001 \003(\0132*.mc.jabbe" +
      "r.proto.DelayChipStateProto.entry\032@\n\005ent" +
      "ry\022\026\n\016remainingDelay\030\001 \001(\r\022\021\n\tdirection\030" +
      "\002 \001(\r\022\014\n\004data\030\003 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mc_jabber_proto_DelayChipStateProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mc_jabber_proto_DelayChipStateProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mc_jabber_proto_DelayChipStateProto_descriptor,
        new java.lang.String[] { "Entries", });
    internal_static_mc_jabber_proto_DelayChipStateProto_entry_descriptor =
      internal_static_mc_jabber_proto_DelayChipStateProto_descriptor.getNestedTypes().get(0);
    internal_static_mc_jabber_proto_DelayChipStateProto_entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mc_jabber_proto_DelayChipStateProto_entry_descriptor,
        new java.lang.String[] { "RemainingDelay", "Direction", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
